# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session:
        # start sessions when you read/write them
        enabled: true
        cookie_path: '/'                   # site‑wide
        cookie_lifetime: 604800            # 7 days
        cookie_samesite: lax               # works over HTTP localhost
        cookie_secure: false               # false for HTTP dev; set to true in prod
        # cookie_domain: ~                 # nil → current host (127.0.0.1)
