gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000                                  # 30 days in seconds
    firewall: api                                 # must match your API firewall name
    user_provider: app_user_provider              # your provider service ID
    single_use: true                              # one‑time use refresh tokens (optional)

    # Cookie settings
    # token_parameter_name: AUTHENTICATION
    cookie:
        enabled:       true
        path:          '/'              # ← Scope to entire app
        domain:        'localhost'      # ← Match your frontend host
        secure:        false            # ← false for HTTP dev
        http_only:     true
        same_site:     'none'           # ← allow cross-site