lexik_jwt_authentication:
    secret_key:     '%env(resolve:JWT_SECRET_KEY)%'   # ← not "private_key_path"
    public_key:     '%env(resolve:JWT_PUBLIC_KEY)%'   # ← not "public_key_path"
    pass_phrase:    '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # in seconds, default is 3600

    # Tell Lexik to read the refresh token from the cookie:
    # token_extractors:
    #     authorization_header:
    #         enabled: true
    #     cookie:
    #         enabled: true
    #         name:    '%env(JWT_REFRESH_COOKIE_NAME)%'


    token_extractors:
        authorization_header:
            enabled: true
            prefix: 'Bearer'
            name: 'Authorization'
        cookie:
            enabled: false

             # Make sure no Set-Cookie directives are ever emitted
    set_cookies: []  
    # (this also ensures the token stays in the JSON body)
    remove_token_from_body_when_cookies_used: false  

    # (Optional) Automatically set access token cookie on login
    # set_cookies:
    #     ACCESS_TOKEN: ~