controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    
stripe_webhook:
    path: /api/webhook
    controller: App\Controller\WebhookController::handle

